### ISSUE TITLE
Significant points are filtered out

### ISSUE THREAD

**Issue by SleepyPrince** [michael-mueller-git/Python-Funscript-Editor#10] opened 2021-09-24 03:52 UTC
The current implementation of [get_local_max_and_min_idx](https://github.com/michael-mueller-git/Python-Funscript-Editor/blob/35711563e12753b543a128a6a4b61cad870013e6/funscript_editor/algorithms/signalprocessing.py#L68) only saves a point when it passes the current moving average. When there is a slack period between 2 points in the same region (both lower or both upper), the latter point gets filtered out which causes incorrect representation of the movement.
![action](https://user-images.githubusercontent.com/670216/134614307-09063669-cdcb-4018-9095-03688a8f2afc.png)
For the example above, green is actual movement and orange is generated movement.
Whether a slack/pause shall be filtered or not shall be determined by a time threshold parameter. (e.g. first short pause at the top)

**Comment by michael-mueller-git** [comment] 2021-09-26 10:45
Yes, this problem is known to me and I have already spent several hours on it in the past but have not yet found a satisfactory solution.

One problem is that an algorithm often works well on synthetic data but performs poorly on real data. For example, I have designed an algorithm that compares the rolling standard deviation with the abs value of second derivative to identify the significant points. For synthetic data the algorithm works very well:

![syntetic_data](https://user-images.githubusercontent.com/86192240/134804152-eb312046-0540-460f-8089-958b922001dd.png)

But on the real tracking signals, the results do not look satisfactory.:

![real_data](https://user-images.githubusercontent.com/86192240/134804146-bccad4f1-87ed-4731-9126-94994666d1ee.png)

But maybe I can merge the results of this detection with the current detection+ threshold and insert missing points...

--

If someone knows an algorithm to reliably detect such points in the signal it would be great to send me a name or link.

**Comment by Noise973** [comment] 2021-09-26 13:35
What happens if you smooth out the data through a first-pass standalone approximation, then run it through your algorithm?

Instead of a scale of 0 - 100 by ones, how about a scale of 0 - 100 by fives?

So a "93" would be rounded to 95, et cetera. It would get rid of a lot of those fine data points and smooth out a lot of the noise.

Sure, you'd lose signal detail, but you're talking about only losing a half of a centimeter of real-world resolution in toy movement, at worst.

**Comment by michael-mueller-git** [comment] 2021-09-26 14:19
@Noise973  I tried it but I am not sure if I understood you correctly. In the picture the result with preprocessing:

![Discretized](https://user-images.githubusercontent.com/86192240/134811610-a856a1e1-ce29-4690-8219-e06b9820c791.png)

The problem is that deriving erratic signals is very bad. I have also tried to use a moving average, but that has also given no advantages. Perhaps I have misunderstood your suggestion...

**Comment by Noise973** [comment] 2021-09-26 14:33
On the other hand, that "Discretized Signal" chart in the middle doesn't look too bad all by itself. Tracks well, no extreme jumps, and if you did a filter of some sort to take out the very-short-period jaggies, it might end up being a decent script.

Something like "if two consecutive points have the same vertical value, average them down to one point."

You could call it the "lazy algorithm."

**Comment by michael-mueller-git** [comment] 2021-09-26 14:55
@Noise973  You mean I should output all changed points? - The problem is that a lot of device can not handle this amount of points. Therefore i have to reduce the number of Points. The best would be if we can create an algorithm which detect all significant points. 

The search criterion would be:
- The Dynamic time warping (DTW) of the new Points with linear interpolation between them is minimal
- And the number of required points is minimal

**Comment by Noise973** [comment] 2021-09-26 15:09
I think something like that might be a good tactic for many videos.

You can see a lot of extra positional noise in many cases (man+woman+camera movement), so throwing out or smoothing a lot might work better for those cases.

**Comment by SleepyPrince** [comment] 2021-09-26 16:32
I understand this is a complicated issue to tackle, and I don't believe there will be a perfect algorithm for all situations.
I think I am currently only looking for a lazy/simple algorithm with some change point prediction if the capture points are before and after the actual change point.
On the other hand, if we are to utilize OFS and its lua api, it is not a bad idea to output all changed points or even all capture points and then apply filter afterwards in OFS. That way it will be more flexible and Python Funscript Editor can focus on how to capturing the action accurately.

**Comment by Noise973** [comment] 2021-09-26 17:25
Maybe just have multiple options.

"Did A work? Great. If it didn't work, choose option B. If that doesn't work, Option C."

Might be easier and faster to make than to try and create an all-things-for-everyone solution.

**Comment by michael-mueller-git** [comment] 2023-01-13 20:09
With implementation of #19 this should no longer an problem. Closing Now

**Closed as completed by michael-mueller-git** 2023-01-13 20:09 UTC
Labels: enhancement
